easy_bugsnag:
    api_key: '%env(for_build:BUGSNAG_API_KEY)%'

    app_name:
        enabled: true
        env_var: 'AWS_ECS_TASK_NAME'

    aws_ecs_fargate:
        enabled: true

    session_tracking:
        enabled: true
        exclude_urls:
            - '^/ping'
        messenger_message_count_for_sessions: true

    worker_info:
        enabled: true
