name: Update Flex endpoint

on:
    push:
        branches:
            - master

defaults:
    run:
        shell: bash

jobs:
    update:
        name: Update Flex endpoint
        runs-on: ubuntu-latest

        steps:
            -   uses: eonx-com/actions-checkout@v2
            -   run: git fetch --prune --unshallow

            -
                name: Install tools
                run: |
                    git config --global user.email "nathan.page@eonx.com"
                    git config --global user.name "natepage"
                    cd .github
                    wget -q -O recipes-checker.zip https://codeload.github.com/symfony-tools/recipes-checker/zip/refs/heads/main
                    unzip recipes-checker.zip
                    cd recipes-checker-main
                    composer install --ansi --no-dev

            -
                name: Update Flex endpoint
                run: |
                    mkdir .github/flex-endpoint
                    git ls-tree HEAD */*/* | php .github/recipes-checker-main/run generate:flex-endpoint ${{ github.repository }} master flex/main .github/flex-endpoint
                    git switch flex/main
                    git rm -q *.json
                    mv .github/flex-endpoint/*.json .
                    git add *.json
                    git commit -m 'Update Flex endpoint' || true
                    git push origin -f flex/main
