<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'EonX\EasyMonorepo\Console\Commands\ExportPackagesAsJsonCommand' shared autowired service.

return $this->services['EonX\\EasyMonorepo\\Console\\Commands\\ExportPackagesAsJsonCommand'] = new \EonX\EasyMonorepo\Console\Commands\ExportPackagesAsJsonCommand();
