<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'EonX\EasyMonorepo\Console\MonorepoApplication' shared autowired service.

return $this->services['EonX\\EasyMonorepo\\Console\\MonorepoApplication'] = new \EonX\EasyMonorepo\Console\MonorepoApplication(new RewindableGenerator(function () {
    yield 0 => ($this->services['EonX\\EasyMonorepo\\Console\\Commands\\ExportPackagesAsJsonCommand'] ?? ($this->services['EonX\\EasyMonorepo\\Console\\Commands\\ExportPackagesAsJsonCommand'] = new \EonX\EasyMonorepo\Console\Commands\ExportPackagesAsJsonCommand()));
}, 1));
