<?php
declare(strict_types=1);

namespace EonX\EasyMonorepo\Release;

use GuzzleHttp\ClientInterface;
use PharIo\Version\Version;
use Symplify\ChangelogLinker\ValueObject\Option as ChangelogLinkerOption;
use Symplify\MonorepoBuilder\Release\Contract\ReleaseWorker\ReleaseWorkerInterface;
use Symplify\MonorepoBuilder\Split\Git\GitManager;
use Symplify\PackageBuilder\Parameter\ParameterProvider;
use Symplify\SmartFileSystem\SmartFileSystem;

final class AutoGeneratedReleaseNotesWorker implements ReleaseWorkerInterface
{
    /**
     * @var \Symplify\MonorepoBuilder\Split\Git\GitManager
     */
    private $gitManager;

    /**
     * @var \GuzzleHttp\ClientInterface
     */
    private $httpClient;

    /**
     * @var \Symplify\PackageBuilder\Parameter\ParameterProvider
     */
    private $parameterProvider;

    /**
     * @var \Symplify\SmartFileSystem\SmartFileSystem
     */
    private $smartFileSystem;

    public function __construct(
        GitManager $gitManager,
        ClientInterface $httpClient,
        ParameterProvider $parameterProvider,
        SmartFileSystem $smartFileSystem
    ) {
        $this->gitManager = $gitManager;
        $this->httpClient = $httpClient;
        $this->parameterProvider = $parameterProvider;
        $this->smartFileSystem = $smartFileSystem;
    }

    public function getDescription(Version $version): string
    {
        return \sprintf('Use github to generate release notes for %s', $version->getVersionString());
    }

    /**
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    public function work(Version $version): void
    {
        $filename = \sprintf(__DIR__ . '/../../secret/release_%s.md', $version->getVersionString());
        $content = $this->getAutoGeneratedReleaseNotes($version);

        // Remove title generated by GitHub
        $content = \str_replace("## What's Changed\n", '', $content);

        $this->smartFileSystem->dumpFile($filename, $content);
    }

    /**
     * @throws \GuzzleHttp\Exception\GuzzleException
     */
    private function getAutoGeneratedReleaseNotes(Version $version): string
    {
        $currentBranch = $this->gitManager->getCurrentBranch();
        $githubToken = $this->parameterProvider->provideParameter(ChangelogLinkerOption::GITHUB_TOKEN);
        $url = 'https://api.github.com/repos/eonx-com/easy-monorepo/releases/generate-notes';

        $options = [
            'headers' => [
                'accept' => 'application/vnd.github.v3+json',
                'authorization' => \sprintf('Token %s', $githubToken),
            ],
            'body' => \json_encode([
                'tag_name' => $version->getVersionString(),
                'target_commitish' => $currentBranch,
            ]),
        ];

        $response = $this->httpClient->request('POST', $url, $options);
        $responseArray = \json_decode($response->getBody()->getContents(), true);

        return $responseArray['body'];
    }
}
