easy_activity:
    table_name: activity_logs

    disallowed_properties:
        - updatedAt

    subjects:
#        App\Entity\SomeEntity:
#            allowed_properties:
#                - content
#                - description
#            disallowed_properties:
#                - author
#            nested_object_allowed_properties:
#                App\Entity\SomeAnotherEntity:
#                    - processingDate
#
