<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV7Vhfxq\StubsEonX_EasyCore_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV7Vhfxq/StubsEonX_EasyCore_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer.php') {
    touch(__DIR__.'/ContainerV7Vhfxq.legacy');

    return;
}

if (!\class_exists(StubsEonX_EasyCore_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false)) {
    \class_alias(\ContainerV7Vhfxq\StubsEonX_EasyCore_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, StubsEonX_EasyCore_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false);
}

return new \ContainerV7Vhfxq\StubsEonX_EasyCore_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer([
    'container.build_hash' => 'V7Vhfxq',
    'container.build_id' => '097b68b9',
    'container.build_time' => 1583838350,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV7Vhfxq');
