<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxPu8Pr\StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxPu8Pr/StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCxPu8Pr.legacy');

    return;
}

if (!\class_exists(StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false)) {
    \class_alias(\ContainerCxPu8Pr\StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false);
}

return new \ContainerCxPu8Pr\StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer([
    'container.build_hash' => 'CxPu8Pr',
    'container.build_id' => 'b09b4eae',
    'container.build_time' => 1580939753,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxPu8Pr');
