<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTUrR4ZF\StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTUrR4ZF/StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer.php') {
    touch(__DIR__.'/ContainerTUrR4ZF.legacy');

    return;
}

if (!\class_exists(StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false)) {
    \class_alias(\ContainerTUrR4ZF\StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer::class, false);
}

return new \ContainerTUrR4ZF\StubsEonX_EasySecurity_Tests_Bridge_Symfony_Stubs_KernelStubTestDebugContainer([
    'container.build_hash' => 'TUrR4ZF',
    'container.build_id' => '700c4ae2',
    'container.build_time' => 1581808776,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTUrR4ZF');
