<?php
declare(strict_types=1);

use Symfony\Component\Config\Definition\Configurator\DefinitionConfigurator;

return static function (DefinitionConfigurator $definition) {
    $definition->rootNode()
        ->children()
            ->arrayNode('app_metric')
                ->canBeDisabled()
                ->children()
                    ->stringNode('namespace')
                        ->defaultNull()
                    ->end()
                ->end()
            ->end()
            ->arrayNode('assets_separate_domain')
                ->canBeDisabled()
                ->children()
                    ->stringNode('url')
                        ->defaultValue('%env(ASSETS_URL)%')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('console')
                ->canBeDisabled()
            ->end()
            ->arrayNode('health')
                ->canBeDisabled()
            ->end()
            ->arrayNode('monolog')
                ->canBeDisabled()
            ->end()
            ->arrayNode('sqs')
                ->addDefaultsIfNotSet()
                ->children()
                    ->arrayNode('reset_services')
                        ->canBeDisabled()
                        ->info('Enable resetting Symfony services between serverless message handling.')
                    ->end()
                ->end()
            ->end()
            ->arrayNode('security_headers')
                ->canBeDisabled()
            ->end()
            ->arrayNode('state')
                ->canBeDisabled()
                ->children()
                    ->booleanNode('check')
                        ->defaultTrue()
                        ->info('Enable state check after each invocation.')
                    ->end()
                ->end()
        ->end();
};
