<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

if (in_array(PHP_SAPI, ['cli', 'phpdbg'], true)) {
    return;
}

require dirname(__DIR__, 3).'/vendor/autoload.php';
require __DIR__.'/ContainerZKtq6hj/monorepoEonX_EasyMonorepo_MonorepoKernelDevDebugContainer.php';

$classes = [];
$classes[] = 'EonX\EasyMonorepo\Console\Commands\ExportPackagesAsJsonCommand';
$classes[] = 'EonX\EasyMonorepo\Console\MonorepoApplication';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

Preloader::preload($classes);
