<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZKtq6hj\monorepoEonX_EasyMonorepo_MonorepoKernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZKtq6hj/monorepoEonX_EasyMonorepo_MonorepoKernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZKtq6hj.legacy');

    return;
}

if (!\class_exists(monorepoEonX_EasyMonorepo_MonorepoKernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZKtq6hj\monorepoEonX_EasyMonorepo_MonorepoKernelDevDebugContainer::class, monorepoEonX_EasyMonorepo_MonorepoKernelDevDebugContainer::class, false);
}

return new \ContainerZKtq6hj\monorepoEonX_EasyMonorepo_MonorepoKernelDevDebugContainer([
    'container.build_hash' => 'ZKtq6hj',
    'container.build_id' => 'a7334cbb',
    'container.build_time' => 1611611891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZKtq6hj');
