name: PHP-CI

on: [ push, pull_request ]

jobs:
    coding_standards:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1' ]
                actions:
                    - { name: composer, run: composer check-composer }
                    - { name: monorepo, run: composer check-monorepo }
                    - { name: composer-audit, run: composer audit }
                    - { name: ecs, run: composer check-ecs, cache: ecs }
                    - { name: rector, run: composer check-rector, cache: rector }
                    - { name: phpstan, run: composer check-phpstan, cache: phpstan }

        name: ${{ matrix.actions.name }} (${{ matrix.php }})

        steps:
            -   uses: actions/checkout@v3

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: ${{ matrix.actions.coverage || 'none' }}
                    extensions: pdo_sqlite, openswoole

            -   uses: ramsey/composer-install@v2
            -   uses: ramsey/composer-install@v2
                with:
                    working-directory: quality

            -   if: matrix.actions.cache
                id: cache-quality-tools
                uses: actions/cache@v3
                with:
                    path: quality/var/cache/${{ matrix.actions.cache }}
                    key: ${{ runner.os }}-${{ matrix.php }}-quality-${{ matrix.actions.name }}-${{ github.sha }}
                    restore-keys: ${{ runner.os }}-${{ matrix.php }}-quality-${{ matrix.actions.name }}-

            -   if: matrix.actions.cache && steps.cache-quality-tools.outputs.cache-hit == false
                run: mkdir -p ${{ matrix.actions.cache }}

            -   name: '[CI] Check ${{ matrix.actions.name }} [CI]'
                run: ${{ matrix.actions.run }}
                shell: bash
